/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kdnakt.kotlin.and.java.app

import com.kdnakt.java.MyObject
import com.kdnakt.kotlin.and.java.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))

    val obj = MyObject("key", "foo")
    println(obj)
}
