/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample.kotlin.app

class App {
    val greeting: String
        get() {
            return "Hello Gradle!"
        }
}

fun main() {
    println(App().greeting)
}
